spring:
  jpa:
    properties:
      hibernate:
        default_schema: public
  liquibase:
    enabled: true
    change-log: db/changelog/2024/11/master.yaml

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  datasource:
    username: citronix
    password:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/citronix

  server:
      port: 8081